
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ArticuloConfiguracion' AND COLUMN_NAME = 'PlanDefecto')
BEGIN
    ALTER TABLE ArticuloConfiguracion ADD PlanDefecto NVARCHAR(50) NULL;
END
GO
